#!/bin/bash
set -e

d=$(mktemp -d /tmp/rindex-benchXXX)
git clone . "$d" > /dev/null 2>&1
cd "$d"

cleanup() {
  rm -rf "$d"
}

trap cleanup EXIT

if ! go test -benchmem -run=XXX -bench "^BenchmarkIndexBatch100$" -count 5 > new; then
  cat new
  exit 1
fi

git checkout master > /dev/null 2>&1
go test -benchmem -run=XXX -bench "^BenchmarkIndexBatch100$" -count 5 > old

benchstat old new
