#!/bin/bash
set -e

d=$(mktemp -d /tmp/rindex-benchXXX)
git clone . "$d" > /dev/null 2>&1
cd "$d"

cleanup() {
  rm -rf "$d"
}

count=5
tname='^BenchmarkIndexBatch'

trap cleanup EXIT

if ! go test -benchmem -run=XXX -bench "$tname" -count $count > new; then
  cat new
  exit 1
fi

git checkout master > /dev/null 2>&1
go test -benchmem -run=XXX -bench "$tname" -count $count > old

benchstat old new
