#!/bin/sh

export RESTIC_REPOSITORY=testdata/repo
export RESTIC_PASSWORD=test

rm -rf "$RESTIC_REPOSITORY"
rm -rf "testdata"
rm -rf "blugeindex/testdata"
restic init > /dev/null
restic backup rindex.go fileindexer.go > /dev/null

go test -v . ./blugeindex
